version: '3.9'
services:
  # app serves the UI & API, it registers user interactions into the database (pg)
  app:
    image: maayanlab/playbook-partnership-ui
    build:
      context: .
      dockerfile: Dockerfile.minimal
    deploy:
      # this can be safely replicated if necessary
      replicas: 1
    environment:
    - DATABASE_URL=${DATABASE_URL}
    ports:
    - 3000:3000
  # the singular dispatcher should not be replicated,
  #  it's a lightweight process which sees incoming Processes inserted into
  #  the database and submits jobs. It's possible this can eventually just
  #  become a database trigger.
  dispatcher:
    build:
      context: .
      dockerfile: Dockerfile
    image: maayanlab/playbook-partnership-ui
    command: ["npm", "run", "start:dispatcher"]
    environment:
    - DATABASE_URL=${DATABASE_URL}
  # the workers should be replicated,
  #   they deal with creating "Resolved" entries for submitted Processes.
  worker:
    image: maayanlab/playbook-partnership
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      # this can be safely replicated as necessary
      replicas: 4
    command: ["npm", "run", "start:worker"]
    environment:
    - DATABASE_URL=${DATABASE_URL}
  # the database is used by everything it can be provisioned with
  #  dbmate (`dbmate up`)
  pg:
    image: postgres
    environment:
    - POSTGRES_DB=${POSTGRES_DB}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
    - 5432:5432
